name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Altere para o arquivo de requisitos do seu projeto, se necessário

      - name: Run tests
        run: |
          python -m unittest discover -s tests  # Ajuste o caminho para os seus testes, se necessário
